name: Generate Documentation
on:
  workflow_call:
jobs:
  docs:
    if: github.repository_owner == 'm00nyONE'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate docs with emmylua_doc_cli
        run: |
          cargo install emmylua_doc_cli
          emmylua_doc_cli --input . --output ./docs
      - name: Deploy
        #if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs