name: Tests
on:
  workflow_call:
jobs:
  missing-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check for missing icon files
        run: |
          python3 .github/scripts/tests/check-missing.py
  orphaned-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check for orphaned icon files
        run: |
          python3 .github/scripts/tests/check-orphaned.py
  missing-includes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check for missing includes in LibCustomIcons.addon
        run: |
          python3 .github/scripts/tests/check-includes.py
  duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Check for duplicate definitions
        run: |
          python3 .github/scripts/tests/check-duplicates.py
  multi-use:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Checks if textures are used multiple times
        run: |
          python3 .github/scripts/tests/check-multiuse.py
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Checks if static and animated entries make sense
        run: |
          python3 .github/scripts/tests/check-sanity.py
  texture-properties:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Checks if textures follow the guidelines
        run: |
          python3 .github/scripts/tests/check-texture-properties.py